// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

$version: "2.0"

namespace controlplane

use aws.apigateway#authorizers
use aws.apigateway#integration
use aws.apigateway#requestValidator
use aws.protocols#restJson1
use smithy.framework#ValidationException

/// The cell-based control plane. Manages tenant and cell lifecycle for a
/// multi-tenant SaaS application using the cell deployment model: a cell is
/// a deployment unit containing one shared application deployment plus up to
/// maxTenants tenants, each with its own per-tenant application deployment.
/// Cells are created implicitly by tenant placement; deployments are
/// provisioned by running lifecycle scripts in AWS CodeBuild. All operations
/// require a vendor IdP JWT validated by a Lambda Authorizer.
@title("Cell-Based Control Plane - Tenant Service")
@restJson1
@httpApiKeyAuth(name: "Authorization", in: "header")
@authorizers(
    "vendor-authorizer": {
        scheme: "smithy.api#httpApiKeyAuth"
        type: "token"
        uri: "PLACEHOLDER"
        identitySource: "method.request.header.Authorization"
        // Explicit, not the implicit 300s default: the policy covers the
        // whole stage (cached per token), so the TTL bounds how long a
        // revoked or expired token keeps access. 60s trades some cache hit
        // rate for a tighter revocation window.
        resultTtlInSeconds: 60
    }
)
@integration(type: "aws_proxy", httpMethod: "POST", uri: "PLACEHOLDER")
// API Gateway validates request bodies and parameters against the generated
// OpenAPI schemas before they reach the Lambda integration (AwsSolutions-APIG2).
// The SSDK still re-validates - gateway validation is defence in depth.
@requestValidator("full")
service TenantService {
    version: "2026-09-03"
    resources: [
        Tenant
        Cell
    ]
    errors: [
        ValidationException
        UnauthorizedError
        InternalServerError
    ]
}

// ---------------------------------------------------------------------------
// Common types
// ---------------------------------------------------------------------------

/// Unique tenant identifier (ULID), generated by the control plane at
/// onboarding.
@pattern("^[0-9A-HJKMNP-TV-Z]{26}$")
string TenantId

/// Human-readable tenant name.
@length(min: 1, max: 128)
string TenantName

/// Free-text tenant description.
@length(max: 1024)
string TenantDescription

/// Email address of the tenant's first customer administrator. Pass-through
/// onboarding input: forwarded to the tenant create script as ADMIN_EMAIL
/// and never persisted on the tenant record.
@pattern("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")
@length(min: 3, max: 254)
string EmailAddress

/// ISO 8601 timestamp.
@timestampFormat("date-time")
timestamp IsoTimestamp

/// Lifecycle status of a tenant or cell and its deployment. Transitional
/// statuses (CREATING, UPDATING, DELETING) act as an optimistic concurrency
/// guard: mutations on an in-flight record are rejected with ConflictError.
enum LifecycleStatus {
    /// The create script is running; the deployment is being provisioned.
    CREATING
    /// The deployment is provisioned and operational.
    ACTIVE
    /// The update script is running; the deployment is being re-applied.
    UPDATING
    /// The delete script is running; the deployment is being deprovisioned.
    DELETING
    /// The create script failed; remediation is delete (cleanup) + recreate.
    CREATE_FAILED
    /// The update script failed; update may be retried or the record deleted.
    UPDATE_FAILED
    /// The delete script failed; delete may be retried.
    DELETE_FAILED
}

/// Opaque pagination token.
@length(min: 1, max: 4096)
string PaginationToken

/// Client-supplied idempotency token. Retrying a request with the same
/// token replays the original outcome instead of repeating its side
/// effects. Tokens are unique per logical request (a UUID is typical) and
/// honoured for at least 24 hours.
@length(min: 1, max: 64)
@pattern("^[A-Za-z0-9_-]+$")
string IdempotencyToken

/// Maximum number of items to return in one page.
@range(min: 1, max: 100)
integer MaxResults

// ---------------------------------------------------------------------------
// Shared deployment definition shapes (CodeBuild ProjectSource subset +
// script locations). Stamped onto cell records from deployment configuration
// (ADR-012); tenants carry no source or scripts of their own.
// ---------------------------------------------------------------------------

/// The type of repository that contains the provisioning source.
/// A modelled subset of the AWS CodeBuild ProjectSource type field:
/// CODEPIPELINE and NO_SOURCE are excluded as meaningless for script sources.
enum SourceType {
    /// Source in an AWS CodeCommit repository.
    CODECOMMIT
    /// Source in a GitHub repository.
    GITHUB
    /// Source in a GitHub Enterprise Server repository.
    GITHUB_ENTERPRISE
    /// Source in a GitLab repository.
    GITLAB
    /// Source in a self-managed GitLab repository.
    GITLAB_SELF_MANAGED
    /// Source in a Bitbucket repository.
    BITBUCKET
    /// Source in an Amazon S3 bucket.
    S3
}

/// Location of the provisioning source: an HTTPS clone URL for repository
/// types, or bucket/path for S3, per CodeBuild ProjectSource.location
/// semantics.
@length(min: 1, max: 2048)
string SourceLocation

/// Path to a provisioning script, relative to the source root
/// (for example "scripts/create.sh").
@length(min: 1, max: 1024)
string ScriptPath

/// The build input source for lifecycle provisioning - a modelled subset of
/// the AWS CodeBuild ProjectSource, containing only what StartBuild
/// per-execution overrides need. Stamped onto each cell record at creation
/// from deployment configuration.
structure SourceDefinition {
    /// The repository type containing the provisioning source.
    @required
    type: SourceType

    /// The source location (HTTPS clone URL or bucket/path).
    @required
    location: SourceLocation
}

/// Locations of the three lifecycle scripts within the source, relative to
/// the source root. The matching script is executed in AWS CodeBuild for
/// each lifecycle operation. Empty deployments are represented by explicit,
/// idempotent no-op scripts - all three locations are always required.
structure ScriptLocations {
    /// Script run when the deployment is created.
    @required
    create: ScriptPath

    /// Script run when the deployment is updated (re-applied).
    @required
    update: ScriptPath

    /// Script run when the deployment is deleted (deprovisioned).
    @required
    delete: ScriptPath
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// The requested tenant or cell does not exist.
@error("client")
@httpError(404)
structure ResourceNotFoundError {
    /// Details of what was not found.
    @required
    message: String
}

/// The request conflicts with the record's current state - for example a
/// mutation on an in-flight tenant or cell (CREATING/UPDATING/DELETING), an
/// update from CREATE_FAILED (remediation is delete + recreate), a tenant
/// build while the cell is not ACTIVE, deleting a cell that still holds
/// tenants, or a CreateTenant clientToken reused with different parameters.
@error("client")
@httpError(409)
structure ConflictError {
    /// Details of the conflicting state.
    @required
    message: String
}

/// The caller's vendor IdP JWT is missing, invalid, or insufficient.
@error("client")
@httpError(403)
structure UnauthorizedError {
    /// Details of the authorization failure.
    @required
    message: String
}

/// An unexpected server-side failure - including missing service context or
/// configuration, which indicates a bug at the ingress layer rather than a
/// client error.
@error("server")
@httpError(500)
structure InternalServerError {
    /// Details of the failure.
    @required
    message: String
}
