// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

$version: "2.0"

namespace controlplane

use aws.apigateway#authorizer

// ---------------------------------------------------------------------------
// Cell resource
// ---------------------------------------------------------------------------

/// A cell - a deployment unit containing one shared application deployment
/// plus up to maxTenants tenants, each with its own per-tenant application
/// deployment. Cells are homogeneous by construction: the deployment
/// configuration (source, cell scripts, tenant scripts, maxTenants) is
/// stamped onto the cell record at creation and is immutable for the cell's
/// lifetime (ADR-012). There is deliberately no create operation - cells are
/// created implicitly when tenant placement finds no cell with free capacity
/// (ADR-013).
resource Cell {
    identifiers: {
        cellId: CellId
    }
    read: GetCell
    update: UpdateCell
    delete: DeleteCell
    list: ListCells
}

// ---------------------------------------------------------------------------
// Cell types
// ---------------------------------------------------------------------------

/// Unique cell identifier (ULID), generated by the control plane when tenant
/// placement creates the cell.
@pattern("^[0-9A-HJKMNP-TV-Z]{26}$")
string CellId

/// Maximum number of tenants a cell can hold, stamped from deployment
/// configuration at cell creation (ADR-012).
@range(min: 1)
integer MaxTenants

/// Current number of tenants placed in a cell. Maintained as an atomic slot
/// counter on the cell record - the capacity and occupancy guard (ADR-013).
@range(min: 0)
integer TenantCount

/// A cell as returned by the API: lifecycle status, capacity/occupancy, the
/// stamped deployment definition, and build bookkeeping.
structure CellSummary {
    /// Unique cell identifier.
    @required
    cellId: CellId

    /// Current lifecycle status of the cell and its shared deployment.
    @required
    status: LifecycleStatus

    /// Maximum number of tenants this cell can hold (stamped at creation).
    @required
    maxTenants: MaxTenants

    /// Current number of tenants placed in this cell.
    @required
    tenantCount: TenantCount

    /// The stamped build input source containing the provisioning scripts.
    @required
    source: SourceDefinition

    /// The stamped lifecycle scripts for the shared cell deployment.
    @required
    cellScripts: ScriptLocations

    /// The stamped lifecycle scripts for per-tenant deployments in this cell.
    @required
    tenantScripts: ScriptLocations

    /// ARN of the most recent successful cell-scoped CodeBuild build.
    lastBuildId: String

    /// Failure detail, populated when status is a *_FAILED value.
    statusReason: String

    /// When the cell was created.
    @required
    createdAt: IsoTimestamp

    /// When the cell record was last modified.
    @required
    updatedAt: IsoTimestamp
}

/// A page of cells.
list CellList {
    member: CellSummary
}

// ---------------------------------------------------------------------------
// GetCell - GET /cells/{cellId} -> 200
// ---------------------------------------------------------------------------

/// Returns a cell: the full record including the stamped deployment
/// definition, lifecycle status, and capacity/occupancy. This is the polling
/// endpoint for asynchronous cell lifecycle operations.
@authorizer("vendor-authorizer")
@readonly
@http(method: "GET", uri: "/cells/{cellId}", code: 200)
operation GetCell {
    input := {
        /// The cell to fetch.
        @required
        @httpLabel
        cellId: CellId
    }

    output := {
        /// The requested cell.
        @required
        cell: CellSummary
    }

    errors: [
        ResourceNotFoundError
    ]
}

// ---------------------------------------------------------------------------
// UpdateCell - PUT /cells/{cellId} -> 202
// ---------------------------------------------------------------------------

/// Re-applies the shared cell deployment: no body - sets UPDATING status and
/// starts the provisioning workflow, which runs the cell's stamped update
/// script in AWS CodeBuild. Asynchronous: returns 202 immediately; poll
/// GetCell for the terminal status. Allowed from ACTIVE and UPDATE_FAILED;
/// rejected with ConflictError while the cell is in-flight or CREATE_FAILED -
/// re-running the update script against a half-created shared deployment
/// would break the create/update script contract, so remediation for a
/// failed cell create is tenant delete + cell delete.
@authorizer("vendor-authorizer")
@idempotent
@http(method: "PUT", uri: "/cells/{cellId}", code: 202)
operation UpdateCell {
    input := {
        /// The cell whose shared deployment to re-apply.
        @required
        @httpLabel
        cellId: CellId
    }

    output := {
        /// The cell, now in UPDATING status.
        @required
        cell: CellSummary
    }

    errors: [
        ResourceNotFoundError
        ConflictError
    ]
}

// ---------------------------------------------------------------------------
// DeleteCell - DELETE /cells/{cellId} -> 202
// ---------------------------------------------------------------------------

/// Deprovisions an empty cell. Sets DELETING status and starts the
/// provisioning workflow, which runs the cell's stamped delete script in AWS
/// CodeBuild and removes the cell record on success. Asynchronous: returns
/// 202 immediately; poll GetCell until it returns 404 (deleted) or
/// DELETE_FAILED. Empty cells only: rejected with ConflictError if
/// tenantCount is greater than zero or the cell is in-flight (ADR-014);
/// allowed from ACTIVE and all *_FAILED statuses - the delete script is the
/// cleanup path for partial provisioning.
@authorizer("vendor-authorizer")
@idempotent
@http(method: "DELETE", uri: "/cells/{cellId}", code: 202)
operation DeleteCell {
    input := {
        /// The cell to delete.
        @required
        @httpLabel
        cellId: CellId
    }

    output := {
        /// The cell, now in DELETING status.
        @required
        cell: CellSummary
    }

    errors: [
        ResourceNotFoundError
        ConflictError
    ]
}

// ---------------------------------------------------------------------------
// ListCells - GET /cells -> 200
// ---------------------------------------------------------------------------

/// Lists cells with pagination - the fleet topology view: status and
/// tenantCount/maxTenants per cell. Statuses are always current - terminal
/// state is written by the provisioning workflow, not repaired by readers.
@authorizer("vendor-authorizer")
@readonly
@paginated(inputToken: "nextToken", outputToken: "nextToken", pageSize: "maxResults", items: "cells")
@http(method: "GET", uri: "/cells", code: 200)
operation ListCells {
    input := {
        /// Pagination token from a previous response.
        @httpQuery("nextToken")
        nextToken: PaginationToken

        /// Maximum number of cells to return.
        @httpQuery("maxResults")
        maxResults: MaxResults
    }

    output := {
        /// One page of cells.
        @required
        cells: CellList

        /// Token for the next page, absent on the last page.
        nextToken: PaginationToken
    }
}
