// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

import { awscdk, javascript } from 'projen';

const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.268.0',
  defaultReleaseBranch: 'main',
  github: false,
  name: 'control-plane',
  description: 'The simple cell-based control plane - multi-tenant SaaS sample',
  packageManager: javascript.NodePackageManager.NPM,
  license: 'MIT-0',
  copyrightOwner: 'Amazon.com, Inc. or its affiliates. All Rights Reserved.',
  copyrightPeriod: '',
  projenrcTs: true,
  deps: [
    // Smithy SSDK runtime (generated code in src/smithy imports these -
    // mirror the dependency set of the generated SSDK package.json)
    'tslib@2.8.1',
    '@aws-sdk/core@3.977.9',
    '@smithy/core@3.33.3',
    '@smithy/fetch-http-handler@5.7.2',
    '@smithy/node-http-handler@4.11.3',
    '@smithy/server-common@0.4.2',
    '@smithy/server-apigateway@0.3.3',
    '@smithy/types@4.17.2',
    // Runtime
    'jose@6.2.10', // vendor IdP JWT validation (JWKS) in the Lambda Authorizer
    '@aws-sdk/client-dynamodb@3.1125.0',
    '@aws-sdk/lib-dynamodb@3.1125.0',
    '@aws-sdk/client-sfn@3.1125.0',
    'ulid@3.0.2', // tenant id generation
    // Security linting - AwsSolutionsChecks aspect applied in src/main.ts
    'cdk-nag@3.0.2',
  ],
  devDeps: [
    '@types/aws-lambda@8.10.163',
    'aws-sdk-client-mock@4.1.0',
    // Integ test framework - alpha pinned to the aws-cdk-lib version
    '@aws-cdk/integ-tests-alpha@2.268.0-alpha.0',
    '@aws-cdk/integ-runner@2.205.0',
  ],
});

// Smithy-generated SSDK output is not linted (regenerated by `smithy build`)
project.eslint?.addIgnorePattern('src/smithy/**/*');

// Generated output is not committed - `smithy build` recreates it before compile
project.gitignore.exclude('src/smithy/');

// Local working notes and agent config - not part of the sample
project.gitignore.exclude('TODO.md');
project.gitignore.exclude('.kiro/');

// The integ-runner snapshot is machine output (assertion-provider templates
// plus bundled CDK assets, including a vendored AWS CLI layer) and is NOT
// shipped with the sample: it would carry megabytes of third-party code and
// trip security scanners on generated artifacts. It stays local so
// --update-on-failed keeps re-runs fast; the integ task always runs --force,
// so no workflow depends on a committed snapshot.
project.gitignore.exclude('test/*.snapshot/');

// Regenerate the SSDK + OpenAPI spec from the model before every compile
project.preCompileTask.exec('smithy build');

// ---------------------------------------------------------------------------
// Build-only placeholder deployment context (S3). src/main.ts fails fast when
// the vendor IdP / cellDefinition context is missing, so `npx projen build`
// (which runs `cdk synth` without deploy context) supplies explicit, clearly
// labelled placeholders. These NEVER reach a deployment: `npx cdk deploy`
// runs its own synth with the real `--context` values (see README "Deploy").
// ---------------------------------------------------------------------------
const buildOnlyPlaceholderContext = [
  '--context vendorIdpIssuerUrl=https://build-placeholder.invalid',
  '--context vendorIdpAudience=build-placeholder',
  // Minimal shape that passes the stack's synth-time validation (§10)
  "--context cellDefinition='" + JSON.stringify({
    source: { type: 'GITHUB', location: 'https://github.com/build-placeholder/build-placeholder.git' },
    cellScripts: {
      create: 'scripts/sample-cell/create.sh',
      update: 'scripts/sample-cell/update.sh',
      delete: 'scripts/sample-cell/delete.sh',
    },
    tenantScripts: {
      create: 'scripts/sample-tenant/create.sh',
      update: 'scripts/sample-tenant/update.sh',
      delete: 'scripts/sample-tenant/delete.sh',
    },
    maxTenants: 10,
  }) + "'",
].join(' ');
project.tasks.tryFind('synth:silent')?.reset(`cdk synth -q ${buildOnlyPlaceholderContext}`);
project.tasks.tryFind('synth')?.reset(`cdk synth ${buildOnlyPlaceholderContext}`);

// End-to-end integration test (test/integ.tenant.ts) - deploys real
// infrastructure and drives the API through the full lifecycle (~25 min).
// Must run in EXACTLY ONE explicitly selected Region (README "Deployment
// integration test"): the guard fails fast when AWS_REGION is unset so
// integ-runner's multi-Region defaults can never apply to this test.
const integ = project.addTask('integ', {
  description:
    'Run the deployment integration test in $AWS_REGION (deploys to the current AWS account, ~25 min)',
});
integ.exec(
  'sh -c \'[ -n "$AWS_REGION" ] || { echo "Set AWS_REGION to the single Region to test in (e.g. export AWS_REGION=eu-central-1)"; exit 1; }\'',
);
integ.exec(
  'sh -c \'AWS_DEFAULT_REGION="$AWS_REGION" exec integ-runner --language typescript --parallel-regions "$AWS_REGION" --update-on-failed --force integ.tenant.ts\'',
);

project.synth();
